name: 'WP Self-Host Updater Generator'
description: 'A GitHub Action for WordPress plugin and theme developers to enable self-hosted updates directly from GitHub. It generates a JSON file from the readme.txt, commits it to the repository, and prepares everything to integrate with custom PHP code for managing updates directly in WordPress. Simplify self-hosting with this automated tool.'
author: 'Eduardo Villão <dev@eduardovillao.me>'
inputs:
  github-token:
    description: 'GitHub Token with write permissions'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Generate JSON
      run: |
        node ${{ github.action_path }}/src/create-json.js
      shell: bash

    - name: Commit JSON to Main
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update JSON for version $GITHUB_REF_NAME"
        git push
      shell: bash
    
    - name: Generate release ZIP
      run: |
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        ZIP_NAME="${REPO_NAME}-${GITHUB_REF_NAME}.zip"
        echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
        git archive --format=zip --output=$ZIP_NAME HEAD
      shell: bash
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: "Release ${{ github.ref_name }}"
        body: "Release of the version ${{ github.ref_name }} generated by WP Self-Host Updater Generator."
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ env.ZIP_NAME }}
        asset_name: ${{ env.ZIP_NAME }}
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}