name: 'WP Self-Host Updater Generator'
description: 'A GitHub Action for WordPress plugin and theme developers to enable self-hosted updates directly from GitHub. It generates a JSON file from the readme.txt, commits it to the repository, and prepares everything to integrate with custom PHP code for managing updates directly in WordPress. Simplify self-hosting with this automated tool.'
author: 'Eduardo Villão <dev@eduardovillao.me>'
branding:
  icon: 'package-dependents'
  color: 'blue' 
inputs:
  github-token:
    description: 'GitHub Token with write permissions'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Define vars
      run: |
        echo "USERNAME=${{ github.repository_owner }}" >> $GITHUB_ENV
        echo "REPO=${{ github.event.repository.name }}" >> $GITHUB_ENV
        echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
        echo "FILENAME=${{ github.event.repository.name }}-${{ github.ref_name }}.zip" >> $GITHUB_ENV
      shell: bash

    - name: Generate JSON
      run: |
        node ${{ github.action_path }}/src/create-json.js
      shell: bash

    - name: Commit JSON to Main
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update JSON for version $TAG"
        git push
      shell: bash
    
    - name: Generate release ZIP
      run: |
        git archive --format=zip --prefix=${{ env.REPO }}/ --output=${{ env.FILENAME }} HEAD
      shell: bash
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.TAG }}
        release_name: "Release ${{ env.TAG }}"
        body: "Release of the version ${{ env.TAG }} generated by WP Self-Host Updater Generator."
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ env.FILENAME }}
        asset_name: ${{ env.FILENAME }}
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}