name: 'WP Self-Host Updater Generator'
description: 'GitHub Action for WordPress to enable self-hosted updates, generating JSON from readme.txt for seamless integration.'
author: 'Eduardo Villão <dev@eduardovillao.me>'
branding:
  icon: 'package'
  color: 'blue' 
inputs:
  github-token:
    description: 'GitHub Token with write permissions'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Define vars
      run: |
        echo "USERNAME=${{ github.repository_owner }}" >> $GITHUB_ENV
        echo "REPO=${{ github.event.repository.name }}" >> $GITHUB_ENV
        echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
        echo "FILENAME=${{ github.event.repository.name }}-${{ github.ref_name }}.zip" >> $GITHUB_ENV
      shell: bash
    
    - name: Generate release ZIP
      run: |
        git archive --format=zip --prefix=${{ env.REPO }}/ --output=${{ env.FILENAME }} HEAD
      shell: bash
    
    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      id: release
      with:
        release_name: "Release ${{ env.TAG }}"
        body: "Release of the version ${{ env.TAG }} generated by WP Self-Host Updater Generator."
        file: ./${{ env.FILENAME }}
        asset_content_type: application/zip
        draft: false
        prerelease: false
        token: ${{ inputs.github-token }}
        
    - name: Generate JSON
      run: |
        node ${{ github.action_path }}/src/create-json.js ${{ fromJSON(steps.release.outputs.assets)[0].id }}
      shell: bash

    - name: Commit JSON to Main
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update JSON for version $TAG"
        git push
      shell: bash
