name: 'WP Self-Host JSON Generator'
description: 'A GitHub Action for WordPress plugin and theme developers to enable self-hosted updates directly from GitHub. It generates a JSON file from the readme.txt, commits it to the repository, and prepares everything to integrate with custom PHP code for managing updates directly in WordPress. Simplify self-hosting with this automated tool.'
author: 'Eduardo Villão <dev@eduardovillao.me>'
runs:
  using: 'composite'
  steps:
    - name: Generate JSON
      run: |
        node ${{ github.action_path }}/src/create-json.js
      shell: bash
    
    - name: Generate release ZIP
      run: |
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        ZIP_NAME="${REPO_NAME}-${GITHUB_REF_NAME}.zip"
        git archive --format=zip --output=$ZIP_NAME HEAD
        mv $ZIP_NAME wp-dist/
      shell: bash
    
    - name: Commit JSON to Main
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git checkout main
        git add wp-dist/plugin-data.json
        git commit -m "Update JSON for version $GITHUB_REF_NAME"
        git push origin main
      shell: bash
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: "Release ${{ github.ref_name }}"
        body: "Release generated by WP Self-Host JSON Generator."
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: wp-dist/${{ github.repository }}-${{ github.ref_name }}.zip
        asset_name: ${{ github.repository }}-${{ github.ref_name }}.zip
        asset_content_type: application/zip